{
  "format_version": 2,
  "sksl": {
    "entrypoint": "header_fade_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform vec2 uScreen;\nuniform vec4 uRect;\nuniform float uStart;\nuniform float uFade;\nuniform float uEnd;\nuniform shader uTex;\nuniform half2 uTex_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 p = FLT_flutter_local_FlutterFragCoord();\n    float t = (p.y - uRect.y) / uRect.w;\n    float f = step(uStart, t) * (1.0 - smoothstep(uFade, uEnd, t));\n    vec2 uv = clamp(p / uSize, vec2(0.0), vec2(1.0));\n    vec4 smp = uTex.eval(uTex_size * ( uv));\n    vec3 col = smp.xyz / vec3(max(smp.w, 0.001000000047497451305389404296875));\n    fragColor = vec4(col * f, f);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uScreen",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uRect",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uStart",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uFade",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uEnd",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 6,
        "name": "uTex",
        "rows": 1,
        "type": 12
      }
    ]
  }
}